language: node_js
node_js:
  - "8"

install:
  - npm install

script:
  - npm test
  - npm run doc

after_success:
  - |
      PACKAGE_VERSION=$(node -pe 'require("./package.json").version')
      $(npm bin)/set-up-ssh --key "$encrypted_42099b4af021_key" --iv "$encrypted_42099b4af021_iv" --path-encrypted-key ".travis/deploy_key.enc"
      $(npm bin)/update-branch --commands "npm run doc" --commit-message "Update documents" --directory "docs/jobcan-client/${PACKAGE_VERSION}/" --distribution-branch "gh-pages" --source-branch "master"
